lint:
  multiqc_config: False
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-magflow_logo_light.png
  - docs/images/nf-core-magflow_logo_light.png
  - docs/images/nf-core-magflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - conf/igenomes.config
  - .github/workflows/ci.yml
  - conf/test_full.config
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-magflow_logo_light.png
  - docs/images/nf-core-magflow_logo_light.png
  - docs/images/nf-core-magflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/workflows/linting.yml
  - .gitignore
  nextflow_config:
  - manifest.name
  - manifest.homePage
nf_core_version: 2.14.1
repository_type: pipeline
template:
  prefix: jeffe107
  skip:
  - igenomes
