name: gunc_run
description: Detection of Chimerism and Contamination in Prokaryotic Genomes
keywords:
  - prokaryote
  - assembly
  - genome
  - quality control
  - chimeras
tools:
  - gunc:
      description: Python package for detection of chimerism and contamination in prokaryotic genomes.
      homepage: https://grp-bork.embl-community.io/gunc/
      documentation: https://grp-bork.embl-community.io/gunc/
      tool_dev_url: https://github.com/grp-bork/gunc
      doi: "10.1186/s13059-021-02393-0"
      licence: ["GNU General Public v3 or later (GPL v3+)"]
input:
  - sample:
      type: val
      description: Sample name.
  - files:
      type: directory
      description: Path where the files containing nucleic acid sequence file in FASTA format "*.{fasta,fna,fa}".
      pattern: 
  - change_dot_for_underscore:
      type: string
      description: Output from the process CHANGE_DOT_FOR_UNDERSCORE indicating that dots were removed from the file name.
  - gtdbtk2_db:
      type: string
      description: Output from the process GTDBTK2_DB indicating that GTDB-Tk2 database was downloaded successfully.
  - gunc_db:
      type: string
      description: Output from the process GUNC_DB indicating that GUNC database was downloaded successfully.
output:
  - gunc:
      type: file
      description: Output file with scores for a taxonomic level with the highest CSS score.
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@jfy133"
maintainers:
  - "@jfy133"
