---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "checkm2_databasedownload"
description: CheckM2 database download
keywords:
  - checkm
  - mag
  - metagenome
  - quality
  - completeness
  - contamination
  - bins
tools:
  - "checkm2":
      description: "CheckM2 - Rapid assessment of genome bin quality using machine learning"
      homepage: "https://github.com/chklovski/CheckM2"
      doi: "10.1038/s41592-023-01940-w"
      licence: ["GPL v3"]

output:
  - stdout:
      type: val
      description: Value verifying that the database was downloaded successfully.

authors:
  - "@dialvarezs"
